[pickle] Dump using the highest available protocol
pallets-eco/flask-caching pull request #261
Opened 2021-07-17 00:52 UTC by john-bodley

This PR ensures that all backends use the same protocol (the highest available) for pickling the payload to cache. Some backends currently use the default (4 for Python 3.8) whereas some use 2 and others use the highest protocol available (maximum of 5). 

Per the `pickle` [documentation](https://docs.python.org/3/library/pickle.html#data-stream-format),

> Protocol version 5 was added in Python 3.8. It adds support for out-of-band data and speedup for in-band data. Refer to PEP 574 for information about improvements brought by protocol 5.

it seems there is merit in utilizing the highest available protocol for increased performance.

Note that it seems the protocol is encoded within the dumped object, i.e., one does not need to re-specify the protocol when loading via `pickle.loads(...)`, thus this should be a non-breaking change.

2021-07-17 00:52 UTC, john-bodley commented on flask_caching/backends/memcache.py
> -        serialized = pickle.dumps(value, 2)
I'm uncertain why this was hardcoded as `2`.

2021-07-22 13:26 UTC, sh4nks commented
While I am generally for this PR I am not sure if this might break some applications?

2021-07-22 16:21 UTC, sh4nks requested changes

2021-07-22 16:21 UTC, sh4nks commented on flask_caching/contrib/googlecloudstoragecache.py
> +            value = json.dumps(value, pickle.HIGHEST_PROTOCOL)
pickle isn't used here

2021-07-24 00:58 UTC, john-bodley commented on flask_caching/contrib/googlecloudstoragecache.py
> +            value = json.dumps(value, pickle.HIGHEST_PROTOCOL)
Apologies. I got a tad carried away.

2021-08-02 17:33 UTC, john-bodley commented
@sh4nks regarding,

> While I am generally for this PR I am not sure if this might break some applications?

per [here](https://realpython.com/python-pickle-module/):

> Note: Newer versions of the protocol offer more features and improvements but are limited to higher versions of the interpreter. Be sure to consider this when choosing which protocol to use.
> 
> To identify the highest protocol that your interpreter supports, you can check the value of the pickle.HIGHEST_PROTOCOL attribute.

My take is that by using `pickle.HIGHEST_PROTOCOL` (as opposed to an explicit version—other than -1) ensures safely on a per interpreter level.

2026-08-13 08:34 UTC, john0isaac commented
we use the highest protocol in dumping now in CacheLib. this pull request was created prior to using CacheLib as the backend provider.
I think it's no longer valid since there is no serializers here in flask-caching + it's already done in CacheLib.
@sh4nks it can be closed.

2026-08-13 08:56 UTC, closed without merging